import { readFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';

const TOPICAL_SECTIONS = new Set([
  'Workspaces',
  'Terminal',
  'Repository',
  'Mobile',
  'Notes and Automation',
  'System Status',
  'Server and Security',
  'Fixes',
  'Release Safety',
]);

function sectionBody(body: string, heading: string): string {
  const marker = `## ${heading}`;
  const start = body.indexOf(marker);
  if (start < 0) return '';
  const contentStart = start + marker.length;
  const nextHeading = body.indexOf('\n## ', contentStart);
  return body.slice(contentStart, nextHeading < 0 ? undefined : nextHeading);
}

export function releaseNotesErrors(body: string, version: string, previousVersion?: string): string[] {
  const errors: string[] = [];
  const headings = [...body.matchAll(/^## (.+)$/gm)].map((match) => match[1]!.trim());
  const duplicates = headings.filter((heading, index) => headings.indexOf(heading) !== index);

  if (headings[0] !== 'Highlights') errors.push('The first section must be "Highlights".');
  if (headings.at(-2) !== 'Install' || headings.at(-1) !== 'Full changelog') {
    errors.push('The final sections must be "Install" and "Full changelog".');
  }
  if (duplicates.length > 0) errors.push(`Duplicate sections: ${[...new Set(duplicates)].join(', ')}.`);

  const middleSections = headings.slice(1, -2);
  const qualityIndex = middleSections.indexOf('Quality');
  if (qualityIndex >= 0 && qualityIndex !== middleSections.length - 1) {
    errors.push('The optional "Quality" section must follow every topical section.');
  }
  for (const heading of middleSections) {
    if (heading !== 'Quality' && !TOPICAL_SECTIONS.has(heading)) {
      errors.push(`Unapproved release-note section: "${heading}".`);
    }
  }

  const highlightCount = [...sectionBody(body, 'Highlights').matchAll(/^- /gm)].length;
  if (highlightCount < 2 || highlightCount > 4) errors.push('Highlights must contain between two and four bullets.');

  for (const command of [
    `npx vampire@${version} --token-file ~/.config/vampire/token`,
    `npm install --global vampire@${version}`,
  ]) {
    if (!sectionBody(body, 'Install').includes(command))
      errors.push(`Install is missing the exact command: ${command}`);
  }

  const changelog = sectionBody(body, 'Full changelog');
  if (previousVersion) {
    const comparison = `https://github.com/baealex/vampire/compare/v${previousVersion}...v${version}`;
    if (!changelog.includes(comparison)) errors.push(`Full changelog is missing the exact comparison: ${comparison}`);
  } else if (!changelog.includes('Initial release.')) {
    errors.push('The first release must use "Initial release.".');
  }

  if (/^# /m.test(body)) errors.push('The release body must not repeat the release title as a level-one heading.');
  if (/\[(?:Most important|Second upgrade|Focused outcome|Relevant Area)/.test(body)) {
    errors.push('Release notes still contain template placeholders.');
  }
  if (/^## (?:What's Changed|New Contributors)$/m.test(body) || /\*\*Full Changelog\*\*/.test(body)) {
    errors.push('Release notes contain autogenerated GitHub sections.');
  }

  return errors;
}

async function main(): Promise<void> {
  const [file, version, previousVersion] = process.argv.slice(2);
  if (!file || !version) throw new Error('Usage: check-release-notes.ts <file> <version> [previous-version]');
  const errors = releaseNotesErrors(await readFile(file, 'utf8'), version, previousVersion);
  if (errors.length === 0) {
    console.log(`Release notes passed: ${file}`);
    return;
  }
  for (const error of errors) console.error(`- ${error}`);
  process.exitCode = 1;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await main();
}
