import assert from 'node:assert/strict';
import test from 'node:test';
import { releaseNotesErrors } from './check-release-notes.ts';

test('accepts a convention-compliant release note', () => {
  const body = `## Highlights

- Preserve user data during upgrades.
- Keep destructive actions explicit.

## Quality

- Add regression coverage for migration failures.

## Install

npx vampire@0.13.1 --token-file ~/.config/vampire/token

npm install --global vampire@0.13.1

## Full changelog

https://github.com/baealex/vampire/compare/v0.13.0...v0.13.1
`;
  assert.deepEqual(releaseNotesErrors(body, '0.13.1', '0.13.0'), []);
});

test('rejects generated sections, template placeholders, and wrong install versions', () => {
  const body = `## Highlights

- [Most important user-visible outcome]

## What's Changed

- Internal change

## Install

npx vampire@0.13.0

## Full changelog

**Full Changelog**: https://github.com/baealex/vampire/compare/v0.13.0...v0.13.1
`;

  const errors = releaseNotesErrors(body, '0.13.1', '0.13.0');
  assert.ok(errors.some((error) => error.includes('between two and four')));
  assert.ok(errors.some((error) => error.includes('Unapproved')));
  assert.ok(errors.some((error) => error.includes('npm install --global vampire@0.13.1')));
  assert.ok(errors.some((error) => error.includes('template placeholders')));
  assert.ok(errors.some((error) => error.includes('autogenerated GitHub sections')));
});
